<div class="container-fluid mt-5 mb-5">
   <div class="row">
      <div class="col-md-3 col-sm-4">
         <h1 class="page_title mb-4">Information</h1>
         <div class="card">
            <div class="card-body">
               <ul class="nav nav-pills flex-column mb-auto displayNoneMobile">
                  <li class="nav-item">
                     <a href="https://nexthealth.pk/cms/about-us/" class="nav-link link-dark" aria-current="page">
                        About Us
                     </a>
                  </li>
                  <li>
                     <a href="https://nexthealth.pk/cms/how_to_order/" class="nav-link link-dark">
                        How To Order
                     </a>
                  </li>
                  <li>
                     <a href="https://nexthealth.pk/cms/payment_method/" class="nav-link link-dark">
                        Payment Methods
                     </a>
                  </li>
                  <li>
                     <a href="https://nexthealth.pk/cms/shipping_and_returns/" class="nav-link link-dark">
                        Shipping & Returns
                     </a>
                  </li>
                  <li>
                     <a href="https://nexthealth.pk/cms/terms_of_service/" class="nav-link  active ">
                        Terms of Service
                     </a>
                  </li>
                  <li>
                     <a href="https://nexthealth.pk/cms/privacy_and_security/" class="nav-link link-dark">
                        Privacy & Security
                     </a>
                  </li>
                  <li>
                     <a href="https://nexthealth.pk/cms/contact_us/" class="nav-link link-dark">
                        Contact Us
                     </a>
                  </li>
                  <li>
                     <a href="https://blog.nexthealth.pk/" class="nav-link link-dark">
                        Our Blog
                     </a>
                  </li>
               </ul>
            </div>
         </div>
      </div>
      <div class="col-md-9 ml-sm-auto col-lg-9">
         <main role="main" class="">
            <h1 class="page_title mb-4">Terms Of Service</h1>
            <div class="card">
               <div class="card-body">
                  <div class=""> 
                     <p style="margin: 0in 0in 8pt; line-height: 107%; font-size: 15px; font-family: Calibri, sans-serif; text-align: left;">
	<span style=" "><strong><span style="font-size: 24px; line-height: 107%;">Terms of Service</span></strong></span></p>
<p style="text-align: justify;">
	<span style=" ">Welcome to <a href="https://nexthealth.pk"><u>https://nexthealth.pk</u></a> (hereinafter referred to interchangeably as the "Nexthealth.pk", or "Website", or "We/we" as the expression and context so requires<strong>)&nbsp;</strong>created, managed and operated<strong>&nbsp;</strong>by<strong>&nbsp;</strong>Next Health Services (Private) Limited (the “Company”) a private limited company incorporated at Lahore, Pakistan on 15 May 2019&nbsp;with the primary objective to provide convenient, affordable and secure healthcare solutions and services to its customers via web-based online and e-commerce channel and by building a chain of retail healthcare outlets.&nbsp;The registered office of the Company is located at 18<sup>th</sup> Avenue, Hussain Chowk, C-2, Gulberg 3, Lahore.</span></p>
<p style="text-align: justify;">
	<span style=" ">The following are the Terms of Service, read together with the Privacy and Security Policy, that govern your purchase and use of the products and services (the "Products") from <a href="https://nexthealth.pk"><u>nexthealth.pk</u></a> / Company and constitute a legally binding agreement (the “Agreement”), between you as a customer (hereinafter referred to interchangeably as the “Customer" or “You/you” or ‘User’ as the expression and context so requires<strong>)</strong> on the one hand and Nexthealth.pk / Company on the other hand.</span></p>
<p style="text-align: justify;">
	<span style=" ">This Agreement is an electronic record. Being generated by a computer system it does not require any physical or digital signatures. This document is, hereby, published for access or usage of Nexthealth.pk.</span></p>
<p style="text-align: justify;">
	<span style=" ">“Customer" or “You/you” or ‘User’ mean and include any natural or legal person who simply visits the Website by entering the domain name in any internet browser. Any Products provided by the Website which do not require registration do not absolve you of the contractual relationship established by this Agreement.</span></p>
<p style="text-align: justify;">
	<span style=" ">The use of this Website binds you by these Terms of Service and any other binding document as decided by the Company from time to time and posted on the Website. You are requested to read them carefully before accepting the same and moving forward to using the Website.</span></p>
<p style="text-align: justify;">
	<span style=" ">By visiting, viewing, accessing or otherwise using any of the Products or information created, collected, compiled or submitted to Nexthealth.pk, you are deemed to have agreed to all the following Terms of Service of this Agreement. So, before you use this Website, please read these Terms of Service carefully, as you agree, to be bound by them. If you do not accept these Terms of Service, please do not use this Website.</span></p>
<table style="width: 100%;">
	<tbody>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>1.</strong></span></td>
			<td style="width: 93.3566%;">
				<span style=" "><strong>REGISTERING AND CREATING AN ACCOUNT:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">1.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The usage of our Website including but not limited to ordering, paying and receiving a product except viewing is open to registered users only and subject to conditions listed herein. It is your responsibility to assess that your usage confirms to standards set forth in this Agreement. Accordingly, the Customer is required to register on this Website and set up an account with Nexthealth.pk (the "Account") and provide certain information as prompted before the Customer. All of registration information is protected by our Privacy Policy.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">1.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The Customer represents and warrants that the personal information provided to us for the purposes of registration shall be complete and accurate and that no attempt will be made to enter or register under any false name or alias. Nexthealth.pk may, in its sole discretion and without assigning any reasons, decline to register a User or disallow a user name that it deems offensive or inappropriate for any reason, whatsoever.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">1.3</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Your Account username and password are personal to you. You may not transfer your Account and you will be responsible for the activities associated with your Account. Further, you are solely responsible for protecting the confidentiality of your username and password and any activity under the Account will be deemed to have been done by you. Nexthealth.pk will not be liable for any loss or damages as a result of your failure to maintain the confidentiality of your account credentials. If you suspect any unauthorized use of your Account, you shall immediately notify Nexthealth.pk.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">1.4</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">It is permissible to add multiple addresses and upload multiple prescriptions to one Account.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">1.5</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The registration of membership or usage of our Website is restricted to those above 18 years of age, or to such group that can be termed to have attained 'majority' under the laws of the respective jurisdictions where this Website can be seen and is accessible or to emancipated minors, who possess legal parental or guardian consent so as to be fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">1.6</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The registration of membership or usage of our Website cannot be availed of by those who are deemed Incompetent to Contract under the applicable laws subject to the aforementioned conditions.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">1.7</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">In the case that you provide us with false and inaccurate details or we have reasonable reasons to believe that you have done so, we hold the rights to suspend your Account and/or terminate this Agreement without any notice and without being held liable for the same. We also reserve all rights to deny or restrict access to this Website to any particular person(s) or persons belonging to any geographical location of the country or to block access from a particular internet address at any time without providing any reasons.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">1.8</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You understand and consent that our Website is owned by us and we may automatically upgrade the Website and these Terms of Service shall apply to the upgrades as well. We reserve the right to terminate this Agreement without any notice and suspend the Account without assigning any reason.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>2.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>PRIVACY AND SECURITY POLICY:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">2.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Your personally identifiable information will be used in accordance with our Privacy Policy. To understand our practices, as to how we collect, use and disclose your personally identifiable information, please refer our Privacy Policy, which also governs your visit to Nexthealth.pk.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">2.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We understand the privacy of all information you provide is of a primary importance. This is why we do everything possible to use it carefully and sensibly. This information is never shared with other companies or third party Service Providers.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">2.3</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">All your transactions are secure when you place an order online at Nexthealth.pk. Your personal information is encrypted by using Let's Encrypt SSL (Secure Sockets Layer) Certificate with encryption 256-bit technology before being sent over the Internet, which ensures the privacy and high level of security of all your information.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>3.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>COMMUNICATIONS</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><br>
				</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">By using this Website, it is deemed that you have consented to receive all communications from Nexthealth.pk or by Service Providers on our behalf including but not limited to calls, SMS’s, auto-dialed and/or pre-recorded messages at any time subject to the Privacy Policy for the purposes of clarifications, marketing and promotions. In case you wish to stop the contact with us for the same, you may send us an email to the effect at our designation email address on our Website.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>4.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>ORDER AND PRESCRIPTION POLICY:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">4.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The website allows you to place your orders after your registration by following the ordering process provided on the Website. If a product or medicine requires prescription, you are required to provide your prescription to enable you to complete your order. A prescription is mandatory for all Narcotics and Controlled Substances which includes all prescription medicines as defined by the Ministry of Health, Government of Pakistan. Shipment of the order will not be carried out until we receive a prescription from a qualified healthcare professional.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">4.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Nexthealth.pk is a fully licensed and regulated pharmacy and takes all precautions to strictly abide by the laws and regulations set forth in the dispensing of prescription medications. By placing the order for your prescription medicines, you acknowledge and accept the following terms regarding the purchase of any prescription medicines.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">4.3</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Nexthealth.pk will not dispense any prescription medication without a valid prescription from a licensed physician.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">4.4</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">If you are ordering prescription medication(s), you hereby confirm that you will send us a scanned copy of your valid prescription(s) via any of the methods provided on our website from time to time including email, fax, Whatsapp, courier or by post, and this prescription shall then be subject to the scrutiny of and approval by our qualified Pharmacists.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">4.5</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">If our pharmacists have any questions or concerns about the prescription(s), you hereby authorize them to consult with an external network of doctors about the validity of the prescription.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">4.6</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The drug information provided in the Nexthealth.pk is for informative purposes only and this Website is not intended to provide diagnosis, treatment or medical advice. We are not liable for any adverse effects or harm to you as a result of your reliance on the information on the Website.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">4.7</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Nexthealth.pk requires either the User or Customer or qualified healthcare professional to confirm that he/she is completely aware of the indications, side effects, drug interactions and effects of missed dose or overdose of the medicines he/she orders from us. It is imperative to seek professional advice from your physician before purchasing or consuming any medicine from Nexthealth.pk.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">4.8</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">At Nexthealth.pk, a qualified health professional can order prescription medicines on your behalf based on the prescription provided.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">4.9</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Nexthealth.pk may accept or decline any order placed by a Customer in its absolute discretion without liability to the company.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>5.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>PRICE, SALE AND PAYMENT POLICY:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The use of this Website is free of cost and this includes only the usage of certain services of the Website. You hereby understand that this no charge policy may be amended at anytime at the discretion of the Company. &nbsp;</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The purchase of Products on the Website is subject to payment of price listed on the Website against each Product and you agree to purchase against payment.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.3</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">All payments required to be made by you shall be …. in Pakistan Rupees. The Website will not facilitate transaction with respect to any other form of currency with respect to the purchases made on the Website.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.4</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">While availing any of the payment methods available on the Website, we will not be responsible or assume any liability, whatsoever, in respect of any loss or damage arising directly or indirectly to you due to: (i) Lack of authorization for any transaction(s); or (ii) Exceeding the preset limit mutually agreed by you and between your bank(s); or (iii) Any payment issues arising out of the transaction; or (iv) Decline of transaction for any other reason(s).</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.5</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">All our Product prices include all applicable statutory taxes. These can be changed from time to time by the authorities under law, which will be passed on to the customer.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.6</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We make every effort to make sure that the pricing and availability of Products on our Website is accurate and up to date. Generally, you are liable to pay the price listed after the completion of your order. However, rarely, there may be an error on the pricing of a product or an error related to product availability. In such cases, we are not responsible for any typographical errors and we reserve the right to cancel the sale.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.7</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We also reserve the right to correct any inaccuracies or omissions related to pricing and Product availability/descriptions, even after you have submitted your order, and to change or update any other information at any time without prior notice.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.8</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You can easily pay for your order by following simple payment instructions that are shown at the end of the order or provided by our Website from time to time subject to such conditions as may be prescribed on our Website from time to time.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.9</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Nexthealth.pk reserves the right to discontinue any program or offer on its Website.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.10</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We reserve the right, without prior notice, to limit the order quantity of any Product available on Nexthealth.pk.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.11</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You understand that all Products shall be sold and dispensed by a registered Pharmacist at Nexthealth.pk and/or its affiliates.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">5.12</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">If you are the patient/parent/authorized person on behalf of the patient, you authorize and appoint the Nexthealth.pk and/or its affiliates, as your attorney and agent, to take all steps, sign all documents and to act on your behalf as if you were personally present and acting for yourself for the limited purposes of (i) obtaining a valid prescription for any prescription which you have sent to us; (ii) packaging your prescriptions and delivering them to you; and (iii) take all ancillary steps related to your desired transaction. By making any purchase, you hereby authorize Nexthealth.pk and/or its affiliates to ship the order by courier to your designated location. This authorization shall include, but not be limited to collecting and using your personal and personal health information as reasonably necessary for the fulfillment of your order. "You have read and understand these terms and agree that they shall be binding upon you and your assigns, heirs and personal representatives." If you are the parent/legal guardian/authorized person for the patient disclosed herein, “you affirm that you are over the age of majority, and have full authority to sign for and provide the above representations to the Nexthealth.pk and/or its affiliates on the Patient's behalf."</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>6.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>CANCELLATION, RETURN AND SHIPPING POLICY:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">6.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You cannot edit or change your order once you have completed the process of placing an order and the order ID is generated. But you can cancel your order at any time before the payment is processed. Once you have made the payment, you are liable to pay 15% restocking fee and the remaining amount would be credited back through banking channel. We do not entertain cash refunds.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">6.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We do our best to ensure that the products you order are delivered according to your specifications. However, should you receive an incomplete, damaged or incorrect Product(s), CONTACT US within 24 hours of receiving the Product(s). We will not accept liability for such delivery issues, if you fail to notify us within 24 hours of receipt of the Product(s).</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">6.3</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">A full refund is possible on the return of a Product if (i) the delivered Product is lost or damaged from outside during transit; or (ii) Defective; or (iii) Expired. If the package is damaged on the outside, do not accept the package and do not sign the delivery slip. Simply return the damaged package. Signing of the delivery slip is taken as your consent that the package has not been damaged in transit. &nbsp;</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">6.4</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We also understand that various circumstances may arise leading you to want to return, replace or exchange a Product(s) that is not defective. In these cases, we may allow the return of unopened, unused products after deducting a 15% restocking charge, only if you notify us within 10 working days of receipt subject to exceptions listed herein below.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">6.5</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Cold chain Product(s) and certain Product(s) marked on the Website marked with the precaution “Not returnable for refund or exchange" are not eligible for return, replacement, exchange or refund. &nbsp;</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">6.6</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We do not refund in cash but through banking channel. We try to refund as soon as possible. However, mode and time of refund may vary depending upon the payment method, you have used. &nbsp;</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">6.7</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">In order to request for a refund, simply CONTACT US your order details, including the reason why you are requesting a refund? We take customer feedback very seriously and use it to constantly improve our quality of service. In case the stock has been dispatched, refund policy will not be affected until allowed on re-examination of the product returned. We will only accept the product in the condition that it is dispatched with all seals and bar codes intact.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">6.8</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We deliver only in Pakistan. You can place an order from outside of Pakistan and have it shipped at any address anywhere in Pakistan. You are required to add an additional address in Pakistan in your Account and select the relevant address at the time of order processing.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">6.9</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We deliver your order through leading courier and logistics companies. The products are packaged in secure and safe boxes. An invoice regarding your order is included inside the package. Your order is delivered to you within the stipulated time period of your relevant courier company. If you have not received your order once it has been dispatched, you can track your order with your relevant courier by taking the tracking number from us.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">6.10</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Our delivery charges are very competitive and vary from city to city. Applicable delivery charges are shown to you at the time of booking your order.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">6.11</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Delivery times may vary depending on the delivery location as well as the type of product you order.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>7.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>USE OF INFORMATION ON THE WEBSITE:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">7.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The information on this Website is not a substitute for professional medical advice or treatment for specific medical conditions. It is important that you do not make medical decisions and you should always seek the advice from qualified healthcare professional with any questions you may have about your medical condition.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">7.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We do not endorse any views or opinions that may be included in the Website Content or other information provided through on the Website regarding the Product(s) or otherwise. Your submission of questions or reviews on our Products does not constitute a professional relationship between you and us.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>8.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>RIGHT TO OWN CONTENT:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">8.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The content on this Website which includes all text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, design documents, and artwork is our content (hereinafter referred to as the “Content”). The Website may contain links to content of third party websites that are not associated with us. We have no control over any third party user generated content as we are merely an intermediary for the purposes of such content. In the event, if any of the third party content infringes any Intellectual Property of any person, the third party shall be solely responsible for any loss caused and we shall not be liable. You may send as an email at our designated email address on our Website to report any such content.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><span style="color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;">8.2</span></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Other than that when expressly allowed, any use of our Content and it being reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way including ‘mirroring’ to any other computer, server, website or other medium for publication or distribution or for any commercial enterprise, without our express prior written consent is not allowed.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><span style="color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;">8.3</span></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The Content that you upload or post on this Website will become our property and you grant us the worldwide, perpetual and transferable rights in such Content. We shall be entitled to, consistent with our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use, forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include any Content you provide and are not entitled to any payment or other compensation for such use. You also grant us the right to sub-license these rights, and the right to bring an action for infringement of these rights. We reserve the right to edit or remove any material submitted to this Website, or stored on our servers, or hosted or published upon this Website.&nbsp;</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><span style="color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;">8.4</span></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Those posting any form of User Content on this Website must verify the truthfulness and authenticity of the particulars of the Content, including the time, place and nature. Before allowing such Content to be posted on the Website, we have the right and authority to verify the accuracy of such particulars related to the Content with the respective sources provided by the User posting such Content, if we feel that there is a need to check such accuracy. We have the right to upload Content on behalf of third parties, subsequent to collecting such information and verifying it if we deem it necessary. Notwithstanding this, we can in no way be held liable for any false or misleading information.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><span style="color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;">8.5</span></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">In case any Content is considered to be unlawful or against the law within any jurisdiction in which our Website can be seen and accessed, it shall be removed forthwith by us on being intimated by the authorities of the respective jurisdiction that any of such Content is deemed unlawful. We cannot be held liable or questioned for the same.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>9.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>USER OBLIGATIONS:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">9.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You are a restricted user of this Website. You are bound not to cut, copy, distribute, modify, recreate, reverse engineer, distribute, disseminate, post, publish or create derivative works from, transfer, or sell any information or software obtained from the Website. With our prior permission limited use may be allowed. For the removal of doubt, it is clarified that unlimited or wholesale reproduction, copying of the Content for commercial or non-commercial purposes and unwarranted modification of data and information within the Content of the Website is not permitted. You shall not, nor allow third parties on your behalf to (i) make and distribute copies of the Website (ii) attempt to copy, reproduce, alter, modify, reverse engineer, disassemble, decompile, transfer, exchange or translate the Website; or (iii) create derivative works of the Website of any kind whatsoever.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">9.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You agree not to access (or attempt to access) the materials or services by any means other than through the interface that is provided by the Website. The use of deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Content, or in any way, reproduce or circumvent the navigational structure or presentation of the Website, materials or any Content, to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Website is not permissible. You acknowledge and agree that by accessing or using the Website or services, you may be exposed to content from other users that you may consider offensive, indecent or otherwise objectionable. We disclaim all liabilities arising in relation to such offensive content on the Website. Further, you may report such offensive content by sending us an e-mail to our designated e-mail address on this website.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">9.3</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">This Website by nature allows you to upload information; you undertake to ensure that such material is in accordance with applicable laws. Further, you undertake not to: <br>
				(i) Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of others; (ii) Engage in any activity that interferes with or disrupts access to the Website or the services (or the servers and networks which are connected to the Website); (iii) Impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity; (iv) Publish, post, disseminate, any information which is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever; or unlawfully threatening or unlawfully harassing; (v) Post any file that infringes the copyright, patent or trademark of other legal entities; (vi) Upload or distribute files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of the Website or another's computer; (vii) Download any file posted by another user of a service that you know, or reasonably should know, cannot be legally distributed in such manner; <br>
				(viii) Probe, scan or test the vulnerability of the Website or any network connected to the Website, nor breach the security or authentication measures on the Website or any network connected to the Website; (viii) Reverse look-up, trace or seek to trace any information on any other user, of or visitor to, the Website, or any other customer of the Website, including any account not owned by you, to its source, or exploit the Website or service or information made available or offered by or through the Website, in any way whether or not the purpose is to reveal any information, including but not limited to personal identification information, other than your own information, as provided for by the Website; (ix) Disrupt or interfere with the security of, or otherwise cause harm to, the Website, systems resources, accounts, passwords, servers or networks connected to or accessible through the Website or any affiliated or linked sites; (x) Collect or store data about other users in connection with the prohibited conduct and activities set forth in this Section; (xi) Use the Website or any material or Content for any purpose that is unlawful or prohibited by these Terms of Service, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Website or other third parties; (xii) Violate any code of conduct or other guidelines, which may be applicable for or to any particular service; (xiii) Violate any applicable laws or regulations for the time being in force within or outside Pakistan; (xiv) Violate the Terms of Service including but not limited to any applicable Additional Terms of the Website contained herein or elsewhere; (xv) Violate any code of conduct or other guidelines, which may be applicable to any particular service; (xvi) Threaten the unity, integrity, defense, security or sovereignty of Pakistan, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting to any other nation; (xvii) Publish, post, disseminate information that is false, inaccurate or misleading; violate any applicable laws or regulations for the time being in force in or outside Pakistan; (xviii) Directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force; and (xix) Create liability for us or cause us to lose (in whole or in part) the services of our internet service provider ("ISPs") or other suppliers;</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">9.4</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">While we shall not be held liable or answerable to Users for any such acts on your part, violation of this clause would lead to potential criminal legal action against you, either by other Users of the Website or by us.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">9.5</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You hereby expressly authorize us to disclose any information about you to law enforcement or other government officials, as we, in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury. You understand that we have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Website) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">9.6</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We have no obligation, to monitor the material posted on the Website. We shall have the right to remove or edit any Content that in our sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Service. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE WEBSITE. In no event, shall we assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Website. You hereby represent and warrant that you have all necessary rights in and to all Content which you provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libelous, tortuous, or otherwise unlawful information.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>10.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>INTELLECTUAL PROPERTY RIGHTS:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">10.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">As per the Terms of Service of Nexthealth.pk, the Website grants access to Users/Customers to view the Content solely for visiting, ordering, and communicating only. All materials and Content contained in or displayed on this Website, including, but not limited to, images, designs, information, graphics, illustrations, text, logos and page headers, the selection and arrangements thereof, that are part of this Website are copyrights, trademarks and/or other intellectual properties owned by the Company and are protected by the relevant laws of intellectual property protection. All other trademarks not owned by the Company that appear on this Website are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by the Company.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">10.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You hereby agree that you will not reproduce, duplicate or copy the Content of Nexthealth.pk for any purpose, unless you have been specifically permitted to do so in a separate agreement with this Website.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>11.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You expressly understand and agree that all information, Products and Content included on or otherwise made available to you through this Website are provided by Nexthealth.pk on an "as is" and "as available" basis, either expressed or implied, statutory or otherwise, including the implied warranties of title, non-infringement, merchantability or fitness for a particular purpose and we specifically disclaim warranties of any kind to the maximum extent allowed by the applicable law. You expressly agree that your use of this Website is at your sole risk. Without limiting the foregoing, we make no warranty that (i) Your requirements will be met or that Products provided will be uninterrupted, timely, secure or error-free; (ii) materials, information obtained and results will be effective, accurate or reliable; and (iii) any errors or defects in the Website, services or other Content will be corrected.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The text and information contained on this Website and any reference to resource material is not intended for the diagnosis, treatment, cure or prevention of any disease or disorder, any User may have. The information contained on the Website, or obtained as a consequence of using this Website is provided by Nexthealth.pk in good faith and is not intended as a substitute for any sort of professional medical advice, whatsoever. All users should always seek the advice of their physician, or other qualified healthcare professional before using the Website. Nexthealth.pk / Company and its directors, officers, employees and representatives take absolutely no responsibility for any Product, Content or information that is provided on this Website and assume no liability of any kind, whatsoever, with regard to any arrangements involving the direct provision of services by third parties.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.3</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Nexthealth.pk assumes no responsibility for any damages or viruses that may infect your computer equipment or other property on account of your access to, use of, or browsing this Website.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.4</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Nexthealth.pk has exerted reasonable efforts to ensure that all information published on the Website is accurate at the time of posting. However, there may be errors in such information for which we shall have no liability. We reserve the right to remove or alter any of the information contained on the Website at our sole discretion.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.5</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Nexthealth.pk cannot guarantee the adequacy, currency or completeness of the Website Content. We do not warrant or endorse the effectiveness, quality or safety of the Products available on our Website.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.6</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We disclaim responsibility for any harm to persons resulting from any instructions or Products referred to in the Website. Nexthealth.pk is not associated with any manufacturer of medicines or other Products on the Website. We do not warrant that the Website or its Content will meet your requirements.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.7</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Nexthealth.pk has made every effort to accurately display the colors of products on its Website but the actual color you see will depend on your monitor. We cannot guarantee that your monitor's display of any color will be the same as the color of the Products delivered to you.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.8</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We may let you view our information and communicate with us through other social media services and applications. We explicitly disclaim any responsibility for the terms of use and privacy policies that govern these third-party websites, which are in no way associated with us.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.9</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We accept no responsibility for any loss or damage suffered due to your reliance on the Product reviews posted by our Users.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.10</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Nexthealth.pk reserves the right to modify or withdraw any part of the Website or any of its Content at any time without notice.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.11</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We take all reasonable care to ensure the availability of the Nexthealth.pk Website 24 hours every day, 365 days per year. However, the Website may become temporarily unavailable due to maintenance, server or other technical issues, or for reasons beyond our control. Nexthealth.pk does not warrant uninterrupted access to this Website or any linked website/App. However, we may, but shall not be obliged to, issue a notice when we know of scheduled maintenance of our Website.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.12</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We provide link to third-party websites, our online payment service partners, which process your payments. We are not responsible for the availability or proper functioning of such linked pages or sites, and we will not be held responsible for any loss or inconvenience encountered as a result of using such Website links.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.13</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We shall have no liability related to User Content arising under intellectual property rights, libel, privacy, publicity, obscenity or other laws. We also disclaim all liability with respect to the misuse, loss, modification or unavailability of any User Content.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.14</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The User understands and agrees that any material or data downloaded or otherwise obtained through the Website is done entirely at his/her own discretion and risk and he/she will be solely responsible for any damage to any computer systems or loss of data that results from the download of such material or data. &nbsp;</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.15</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You hereby agree to indemnify, defend and hold harmless Nexthealth.pk / Company and its officers, directors, employees, affiliates, agents, information providers, partners, licensors, advertisers and suppliers from and against all liabilities, claims, losses, expenses, damages and costs, including reasonable legal fees and costs, in connection therewith and interest chargeable thereon asserted against or incurred by us that arise out of, result from, or may be payable by virtue of, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed by you pursuant to these Terms of Service or resulting from any violation of this Agreement, or any activity related to your Account, or any information or material you have submitted or will submit to us in violation of any law or in breach of any third party rights including, but not limited to, claims in respect of defamation, invasion of privacy, or infringement of any other intellectual property right. We reserve the right to exclusively defend and control any claims arising from the above and any such indemnification matters, and you hereby agree to cooperate fully with us in asserting any available defenses. Further, you agree to hold us harmless against any claims made by any third party due to, or arising out of, or in connection with, your use of the Website, any claim that your material caused damage to a third party, your violation of the Terms of Service, or your violation of any rights of another, including any intellectual property rights.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.16</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">In no event shall we, or our officers, directors, employees, partners or suppliers be liable to you or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable or whether or not we have been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty, negligence or other tortious action, or any other claim arising out of or in connection with your use of or access to the Website, Products or Content.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.17</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The content on the Website is general in nature and summarized, and is provided for informational purposes only. The content of the Website, including without limitation, text, copy, audio, video, photographs, illustrations, graphics and other visuals, is for informational purposes only and does not constitute professional advice, or recommendations of any kind.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">11.18</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You do hereby grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty- free, sub-licensable right to exercise the copyright, publicity, and database rights you have in your information, in any media now known or not currently known, with respect to your information to enable us to use the information for the purpose of providing the Products.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><span style="color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;">11.</span>19</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You release and indemnify us and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the Website and specifically waive any claims that you may have in this behalf under any applicable law. Please note that there could be risks in dealing with underage persons or people acting under false pretence.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><span style="color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;">11.20</span></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">From this Website, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply our recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which in our opinion is irrelevant or bad. We assume no liability regarding any claim of any nature resulting from use of such hyperlinks to such external sites.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><span style="color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;">11.</span>21</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You are warned that when you leave this Website, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the privacy policies of these sites as well as their terms of service before engaging in any business or uploading any information. We assume no liability regarding your failure to exercise caution or for any loss occasioned to you in this behalf.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><span style="color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;">11.22</span></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Nexthealth.pk shall, under no circumstances, be held responsible for the therapeutic claims made in relation to advertised Products on this Website. We, in good faith, reproduce information regarding therapeutic claims and mode of action of the advertised medications which is based entirely on the information provided by the manufacturers and suppliers of Product(s) provided to us. If in doubt, the intending user(s) should always consult their healthcare professional for guidance. We make no warranty of any type and assume no liability regarding any loss occasioned to you, in this behalf.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><span style="color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;">11.23</span></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">All the limitations and exclusions in this clause apply to the maximum extent permitted by applicable law.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><span style="color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong>12.</strong></span></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>TERMINATION:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><br>
				</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">You agree that Nexthealth.pk, in its sole discretion and for any or no reason, including without limitation, if you breach these Terms of Service, may terminate your access to and use of the Website, at any time. You agree that any termination of your access to the Website or suspension of your Account may be effected without prior notice, and you agree that Nexthealth.pk shall not be liable to you for any such termination. Your right to use this Website immediately ceases upon termination of your access/use of this Website.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>13.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>DISPUTE RESOLUTION, APPLICABLE LAW AND JURISDICTION:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">13.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">All complaints and disputes involving but not limited to rights conferred, compensation, refunds, and other claims will be resolved through a two-step Alternate Dispute Resolution (“ADR”) mechanism.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">13.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">Once we receive your complaint, our representatives will investigate it within shortest possible time depending upon the nature of the complaint and prepare a report which will be shared with you and the matter will be resolved to your satisfaction in the light of the investigation report. If you are not satisfied, the complaint will be referred to the Mediation Committee consisting of two to three persons set up by the Company, in its sole discretion, which will attempt to resolve it amicably to the mutual satisfaction of the Customer and us. In the event, an amicable mutually agrees resolution of complaint is not effected within thirty (30) days from the date of referral of complaint to the Mediation Committee, the dispute will be referred to a sole arbitrator to be appointed by the Company, and the award passed by such sole arbitrator will be valid and binding on both Parties. The Parties shall bear their own costs for the proceedings, although the sole arbitrator may, in his/her sole discretion, direct either Party to bear the entire cost of the proceedings. The arbitration shall be conducted in English, and the seat of Arbitration shall be the city of Lahore in the Province of the Punjab. You agree that exhausting the ADR mechanism is a condition precedent to avail any other remedy available in law. &nbsp;Why can’t we just say that in case of non-resolution it will be referred to arbitration.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">13.3</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">These Terms of Service and your use of this Website and its Content will be governed by and construed in all respects in accordance with the laws of Pakistan subject to the exclusive territorial jurisdiction of the Courts at Lahore. &nbsp;</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>14.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>MODIFICATIONS TO TERMS OF SERVICE AND CONTENT:</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">14.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We reserve the right to amend these Terms of Service from time to time without further notice to you. Any such amendments we make shall be effective once we post a revised version of these Terms of Service on the Website. It is your responsibility to review the Terms of Service on this Website regularly or before use each time. Your continued use of the Website following the publication of any such changes will constitute your agreement to follow and you will be automatically bound by the amended terms and conditions. Your use of this Website at any time will be governed according to the Terms of Service that applied at the time of your use.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">14.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We may modify, suspend, discontinue or restrict the use of any portion, including the availability of any portion of the Content at any time, without notice or liability. We may deny access to any person or user at any time for any reason. In addition, we may at any time transfer rights and obligations under this Agreement to any affiliate, subsidiary or business unit, or any of their affiliated companies or divisions, or any entity that acquires us.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">14.3</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">We hereby reserve the right to block usage of the Website, if any breach of the Terms of Service is caused by a User. This can in no way be construed as a waiver of any legal right under the laws of Pakistan to claims any damages or initiate any legal proceedings against the User.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" "><strong>15.</strong></span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" "><strong>MISCELLANEOUS</strong></span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">15.1</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The User of the Website shall comply with all the applicable laws, Rules, Regulations in force in Pakistan for using Payment Facility and the Website.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">15.2</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">These Terms of Service will be governed by and construed in accordance with the laws of Pakistan without regard to its conflicts of law provisions. Any failure of the Website / Company to enforce or exercise any provision of this Agreement or related right shall not constitute a waiver of that right or provision.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">15.3</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The headings used in this Agreement are purely for convenience and carry with them no legal or contractual effect in interpretation of this Agreement.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">15.4</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">The recitals to this Agreement constitute an integral part of this Agreement</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">15.5</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">In the event of termination of this Agreement for any reason, you agree that the provisions with respect to limitations on your use of the Content, the license(s) you have granted to the Website / Company and all other provisions for which survival is equitable or appropriate will survive.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">15.6</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">In the case of a conflict between these Terms of Service and the terms of any other Content on this Website or electronic or machine readable statement or policy, these Terms of Service shall prevail. Similarly, in case of a conflict between these Terms of Service and our Privacy Policy, these Terms of Service shall prevail.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">15.7</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">If any provision of these Terms of Service shall be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms of Service and shall not affect the validity and enforceability of any remaining provisions.</span></td>
		</tr>
		<tr>
			<td style="width: 6.5268%; vertical-align: top;">
				<span style=" ">15.8</span></td>
			<td style="width: 93.3566%; text-align: justify;">
				<span style=" ">If you have any questions or comments regarding these Terms of Service, CONTACT US.</span></td>
		</tr>
	</tbody>
</table>
<p></p>
                  </div>
               </div>
            </div>
         </main>
      </div>
   </div>
</div>

